### ISSUE TITLE
Find issues to resolve for this lesson

### ISSUE THREAD

**Issue by weaverbel** [LibraryCarpentry/lc-data-intro#10]
This lesson has now been migrated to the Library Carpentry organisation.

All the issues raised for this lesson are still on the old repo at https://github.com/data-lessons/library-data-intro-DEPRECATED/issues

Find issues to resolve *there* and fix them **here**.

**Comment by drjwbaker** [comment]
Can we close this @ccronje?

**Comment by ccronje** [comment]
Yes I'll close this one @drjwbaker, as the relevant issues have been migrated. Ping @sharilaster @ppival @antonangelo
