### ISSUE TITLE
Re-write to remove use of "I" in the 03-foundations.md lesson.

### ISSUE THREAD

**Issue by jt14den** [LibraryCarpentry/lc-data-intro#11]
Move away from "I" statements in favor of "we" and let's.

**Comment by VasantJ3** [comment]
Hello @ankuhl  , I am Vasant Joseph. I am a class 12 student. I have skills in designing(Photoshop, premiere pro), presentation, and anything which is given to me, which I can do. I am sincere to my work. If there is anything which I can do to help, please inform me. This is my first time at Mozilla global sprint.
I have experience by participating in a variety of hackathons.
I am interested to help.

**Comment by VasantJ3** [comment]
Hello @jt14den   , I am Vasant Joseph. I am a class 12 student. I have skills in designing(Photoshop, premiere pro), presentation, and anything which is given to me, which I can do. I am sincere to my work. If there is anything which I can do to help, please inform me. This is my first time at Mozilla global sprint.
I have experience by participating in a variety of hackathons.
I am interested to help.

**Comment by VasantJ3** [comment]
please tell what to do and i will do it sincerely

**Comment by sharilaster** [comment]
I've proposed a solution as PR #13
