### ISSUE TITLE
Problem working through final exercise in 04-regular-expressions

### ISSUE THREAD

**Issue by icecjan** [LibraryCarpentry/lc-data-intro#110]
I ran into problem when working through the exercise "Extracting a substring in Google Sheets using regex". 
I followed the 2014 Public Library Survey link in step 1 and downloaded a zip file, which contains 3 CSV files. There's no mention in the exercise which file to import to Google Sheets. I checked all three of them but cannot find a LOCATION column in any of the files. I'm not sure if I have downloaded what was intended to be used in this exercise?

**Comment by libcce** [comment]
I can't find it too @icecjan. The file(s) appear to have been updated? Yet another thing for us to look into @ppival @sharilaster @antonangelo @ccronje. For your upcoming workshop, you might want to use the Crossref dataset instead https://raw.githubusercontent.com/LibraryCarpentry/lc-open-refine/gh-pages/data/doaj-article-sample.csv. BTW, I've never done the Google Spreadsheets example. I've switched to using https://regexr.com/ with The Carpentries Code of Conduct. https://github.com/LibraryCarpentry/lc-data-intro/blob/gh-pages/data/swcCoC.md.

**Comment by ppival** [comment]
Wow is it hard to find good examples of dirty data anymore - I guess that's a good thing! :-) I ended up dirtying the 2017 Public Library Survey from the same source and posting the file to the Github repository, and will change the exercise to point to that file.
