### ISSUE TITLE
Error in 04-regular-expressions intro section

### ISSUE THREAD

**Issue by kristindawn** [LibraryCarpentry/lc-data-intro#111]
There is a missing character that will cause confusion to learners in the last paragraph of the opening section of Regular Expressions:

"For example, the period (.) means “match any character”, but if you want to match a period (.) then you will need to use a “" in front of it to signal to the regular expression processor that you want to use the period as a plain old period and not a metacharacter. 

There should be a \ between the empty quotation marks in the middle of that sentence.

**Comment by libcce** [comment]
@kristindawn does this help https://github.com/LibraryCarpentry/lc-data-intro/pull/112 ?

**Comment by kristindawn** [comment]
Perfect, thanks @libcce !
