### ISSUE TITLE
04-regular-expressions - consider using something other than "foobar"?

### ISSUE THREAD

**Issue by kristindawn** [LibraryCarpentry/lc-data-intro#113]
"foobar"is kind of a specific reference to have in these lessons. Is there another real word that could be used as an example?

**Comment by drjwbaker** [comment]
I take the point. But there is value in keeping a nonsense word / placeholder of some kind. I spend a lot of time in lessons trying to make clear which things are vocab that has to be used and which things could be anything - usually done by bashing on the keys for a bit ogidosioirkoaer..

**Comment by kristindawn** [comment]
I don't necessarily have an issue with placeholder words, I have an issue with foobar specifically. Students in our workshops have called out that they recognize that it is in an inside joke used by developers that they don't necessarily get and feels exclusionary. It is also based on US military slang which doesn't seem in the spirit of the Carpentries lessons.

**Comment by drjwbaker** [comment]
Fair enough. Have you used an alternative placeholder? `lorem`?

**Comment by ostephens** [comment]
I don’t have strong feelings either way but I think there’s an argument to use foobar exactly because it’s used by developers. It’s a bit of jargon that is often used in this type of lesson and this lesson could be an opportunity to demistify it.

**Comment by libcce** [comment]
I came across this rant https://dev.to/warrend/no-more-foo-bar-and-baz-56j4. I know reading the comments can be bad sometimes but I thought some of the comments were helpful. For instance, contextualizing it to the audience/venue you are teaching at. There is also a comment about the origin and I originally thought the same @ostephens that it might be a good opportunity to demystify it, why it is used by developers, but I think the military connection gives me pause.  Thanks for bringing this up @kristindawn!

**Comment by ostephens** [comment]
No strong feelings, but:

* If we change it here, we should definitely change it in 05-quiz.md and 06-quiz-answers.md (and to be honest I think the uses there are more problematic in that they generalise where really a real world example would be much more meaningful)
* Note that foo/bar is used in https://github.com/LibraryCarpentry/lc-data-intro/blob/a6b4b2c78f6babe873ae686fedd0978cd8f28c4e/_includes/base_path.html which is part of the Sofware Carpentry template - I'm not raising this as an argument to keep foo/bar anywhere, but it does exemplify how widespread its use is
* Also used in https://github.com/LibraryCarpentry/lc-python-intro/blob/c1bfb5b5cf93780e0ad49edbe4b261f61e818312/_episodes/15-scope.md as part of an error message - I'm not clear why but if we are going to stop using it then it probably needs checking here as well

**Comment by kristindawn** [comment]
Thanks for considering. The military association is the most problematic part for me. There is a ton of new language for folks to learn in Library Carpentry and I think that foobar isn't that useful an addition to that long list if we can take it out. 

If I can help, let me know!

**Comment by ernstki** [comment]
Agreed that the wink-wink reference to the military acronym [FUBAR](https://en.wikipedia.org/wiki/List_of_military_slang_terms#FUBAR) is not great, and never was. There too many other fun things about programmer culture to pass on to get overly sentimental about dropping this one. If students of the LC course see "foo" and "bar" somewhere on the Internet, those are understandable in context as nonsense words; no "lesson" is needed here.

I think `word` or `pattern` would do just fine, or even a real word, like "comb" or "present," which when combined with prefixes and suffixes form many other words, and therefore illustrate the concept of anchoring on word boundaries very nicely.

I can do a PR for this.

Just as a fair warning, the PR will come with "666" replaced with some other number or string, though. This would arise from what I feel is the more problematic association of 666 (however misguided it may be in a biblical scholarship sense) with the [Number of the Beast](https://en.wikipedia.org/wiki/Number_of_the_Beast).
