### ISSUE TITLE
Review 02-jargon-busting.md 

### ISSUE THREAD

**Issue by sauuyer** [LibraryCarpentry/lc-data-intro#115]
Consider referencing NNLM's data thesaurus as a place to look up jargon in post-carpentry situations. This could also serve the purpose of exposing learners to terms that may not have come up during group chats as well. Link to the data thesaurus here: https://nnlm.gov/data/thesaurus

**Comment by libcce** [comment]
Thanks for the suggestion @sauuyer! This PR adds the thesaurus https://github.com/LibraryCarpentry/lc-data-intro/pull/124.
