### ISSUE TITLE
Replace Foundations w/ Why automate? and File naming 

### ISSUE THREAD

**Issue by libcce** [LibraryCarpentry/lc-data-intro#138]
As discussed @ccronje @sharilaster @ppival, Foundations is now two episodes:

- https://github.com/LibraryCarpentry/lc-data-intro/blob/gh-pages/_episodes/09-why-automate.md
- https://github.com/LibraryCarpentry/lc-data-intro/pull/136

The File naming episode is a PR that needs to be approved/merged by one/all of you. If we are fine with this, I can update the episodes to reflect these changes. @sharilaster I included a very basic challenge of working with Markdown in File naming. What do you think? @ccronje I added a link to the UNIX Shell lesson at the end of File naming. Is this what you were thinking?

**Comment by libcce** [comment]
I merged the PR above so the two episodes to consider are:

- Why automate? https://github.com/LibraryCarpentry/lc-data-intro/blob/gh-pages/_episodes/09-why-automate.md
- File naming https://github.com/LibraryCarpentry/lc-data-intro/blob/gh-pages/_episodes/10-file-naming.md

to replace Foundations https://github.com/LibraryCarpentry/lc-data-intro/blob/gh-pages/_episodes/03-foundations.md

As we discussed via our teams site, @sharilaster @ppival @ccronje what do you think? Ready to make this change?

**Comment by sharilaster** [comment]
They look good. I think a different name might be helpful for "File naming" since it also covers plain text -- what about "Machine-friendly practices" or something like that?

**Comment by sharilaster** [comment]
Or "Machine-friendly foundations"?

**Comment by ccronje** [comment]
This all looks good - thanks @libcce @sharilaster! @sharilaster is the title "File naming & formatting" ok?

Would you like me to delete Foundations and renumber the episodes?

**Comment by libcce** [comment]
Hi @ccronje @sharilaster discussion here https://github.com/LibraryCarpentry/lc-data-intro/pull/142 on what happened in the 2nd lesson sprint at CDL.

**Comment by libcce** [comment]
Now that we have an overview lesson https://librarycarpentry.org/lc-overview/ I'm going to close this issue, remove the two new episodes:

Why automate? https://github.com/LibraryCarpentry/lc-data-intro/blob/gh-pages/_episodes/09-why-automate.md
File naming https://github.com/LibraryCarpentry/lc-data-intro/blob/gh-pages/_episodes/10-file-naming.md

I'm leaving Foundations for the moment and opening up another issue for us to review the overview.
