### ISSUE TITLE
Incorporate real Library examples in text & interactive exercise

### ISSUE THREAD

**Issue by jcoliver** [LibraryCarpentry/lc-data-intro#15]
Migrated from data-lessons/library-data-intro-DEPRECATED#27. See discussions there.

**Comment by drjwbaker** [comment]
Bumping. Any maintainer want to take this?

**Comment by ccronje** [comment]
@drjwbaker closing this issue, as the referenced issue concluded OpenRefine lesson has something similar https://github.com/data-lessons/library-data-intro-DEPRECATED/issues/27#issuecomment-305165646.

Discussion on plain text continued in https://github.com/LibraryCarpentry/lc-data-intro/issues/51.

Ping @sharilaster @ppival @antonangelo
