### ISSUE TITLE
Clarifying first regex example

### ISSUE THREAD

**Issue by emilymae** [LibraryCarpentry/lc-data-intro#154]
In the [first episode on Regular Expressions](https://librarycarpentry.org/lc-data-intro/01-regular-expressions/index.html), the example of the `organi[sz]e` regular expression at the end of the first section is a bit confusing. 

There's some inconsistency with the last sentence of the first section where  `reorganise`, `reorganize`, `organises`, `organizes`, `organised`, `organized` are formatted as code, which looks like the regex in the previous sentence, but I believe in this example they are supposed to be other strings that would match.

I would also be interested in helping to restructure the lesson to clarify some simpler concepts first, e.g. capitalizing a word (or not) makes a difference because upper case and lower case are treated as different characters in a string, and that ASCII has special characters for tab, space and newline. Then more complicated concepts like escape characters can be discussed after that. Generally I think it would help to space out introducing the different types of the metacharacters throughout the episode, since it's a lot to take in all at once.

**Comment by ppival** [comment]
Thanks @emilymae. I think the intention of the formatting was simply to make the text stand out, but if you think italics or bold or some other formatting would make it less confusing, please do submit a pull request. :-) Same goes for your other thoughts!
