### ISSUE TITLE
Adding more context to organi[sz]e example

### ISSUE THREAD

**Issue by kylamj** [LibraryCarpentry/lc-data-intro#156]
As part of the checkout process I propose a rephrasing in the Regular Expressions (lesson 1) segment (https://librarycarpentry.org/lc-data-intro/01-regular-expressions/index.html).

The existing training states:

> But it would also match reorganise, reorganize, organises, organizes, organised, organized, etc.

However it does not explain why it would match all those words, instead of just organize and organise.

I propose a change to:

> But because it is looking specifically for all the characters in the document that match that pattern, not just for that word, it would also match reorganise, reorganize, organises, organizes, organised, organized, etc.

**Comment by sharilaster** [comment]
Thank you for the suggestion, @kylamj. I've opened #159 with a version of this edit. Have a look and let us know what you think!

**Comment by ccronje** [comment]
Thanks for the improvements @kylamj @sharilaster, I've merged @sharilaster's fix and am closing this issue. Please re-open if you need to.
