### ISSUE TITLE
Rephrasing the contexts in which regex is useful

### ISSUE THREAD

**Issue by kylamj** [LibraryCarpentry/lc-data-intro#157]
I found some of the phrasing in this lesson odd - it briefly switches into the first person, which is not otherwise used in the training.

The existing training states:

> This logic is useful when you have lots of files in a directory, when those files have logical file names, and when you want to isolate a selection of files. It can be used for looking at cells in spreadsheets for certain values, or for extracting some data from a column of a spreadsheet to make new columns. I could go on. The point is, it is useful in many contexts.

I find the use of "I" unusual in this context, and the following statement does not clarify the many uses of regex for learners.

I propose a change to:

> This logic is useful when you have lots of files in a directory, when those files have logical file names, and when you want to isolate a selection of files. It can be used for looking at cells in spreadsheets for certain values, or for extracting some data from a column of a spreadsheet to make new columns. There are many other contexts in which regex is useful when using a computer to search through a document, spreadsheet, or file structure.

**Comment by sharilaster** [comment]
Hello @kylamj, I think I have proposed a solution with #160. You can compare the two versions and see if this fix addresses your concerns?

(Maintainers, sorry I made a bit of a muddle with this PR. It's an adventure every time!)

**Comment by ccronje** [comment]
Thanks for the improvements all, I've merged and am closing this issue. Please re-open if you need to.
