### ISSUE TITLE
Use of forward slashes

### ISSUE THREAD

**Issue by PhilReedData** [LibraryCarpentry/lc-data-intro#164]
In [episode 1](https://github.com/LibraryCarpentry/lc-data-intro/blob/gh-pages/_episodes/01-regular-expressions.md), in the "Case insensitivity" exercise, the solution includes a forward slash delimiter at the start of the regex, as well as the end. Previously it explains the use at the end, now we are also using it at the start. 

Should we explain the use of forward slashes, as they appear in the suggested tools wrapping all regex strings? (I think this is how Javascript uses it.) I don't want to confuse people with too many implementations, perhaps we should just explain it a bit better in the exercise above.

**Comment by sharilaster** [comment]
@PhilReedData I think it would depend on if that's too much detail up front or not. Thoughts from others? @ppival @ccronje @libcce

**Comment by ccronje** [comment]
@PhilReedData @sharilaster that's a good idea providing more explanation in the example. Could you please suggest an improvement, and we can review? There is brief mention of the forward slash under 'Using special characters in regular expression matches' but could easily be missed. Addressing in the example is probably the best place to expand on it.

**Comment by PhilReedData** [comment]
I shall suggest an improvement (fork and PR), thanks everyone.

**Comment by ccronje** [comment]
Thanks @PhilReedData
