### ISSUE TITLE
Typo in Keyword END --> AND

### ISSUE THREAD

**Issue by jkreklow** [LibraryCarpentry/lc-data-intro#175]
In episode 3 of LC lesson SQL Intro, there is a confusing typo in the Objectives section. The Keyword END is wrong here and should be changed to AND.

Write queries that SELECT data based on conditions, such as END, OR, and NOT.

--> Write queries that SELECT data based on conditions, such as **AND**, OR, and NOT.

https://librarycarpentry.org/lc-sql/03-filtering/index.html

**Comment by libcce** [comment]
Thanks @jkreklow I've created this PR https://github.com/LibraryCarpentry/lc-sql/pull/110 in the LC SQL lesson for you.
