### ISSUE TITLE
Recommend remove 01 "Introduction to Library Carpentry"

### ISSUE THREAD

**Issue by emcaulay** [LibraryCarpentry/lc-data-intro#18]
@jt14den and I discussed, and we feel that this section is not in line with other lessons. Introduction to Library Carpentry should be covered outside of a lesson. But before removing, I'd prefer to get some comments in favor / not in favor. Even if it's just @jt14den

**Comment by ccronje** [comment]
I agree @emcaulay @jt14den. It makes sense to extract the 'introduction to Library Carpentry' now that the number of lessons has grown, and the lc-data-intro lesson may not be the first to be taught at a workshop.

Linking this issue with https://github.com/LibraryCarpentry/lc-data-intro/issues/9

**Comment by ccronje** [comment]
Closing this issue - see https://github.com/LibraryCarpentry/lc-data-intro/issues/9 for further details on rewriting episode 1.
