### ISSUE TITLE
Use the same term for Lines 55-59

### ISSUE THREAD

**Issue by fmichonneau** [LibraryCarpentry/lc-data-intro#194]
I'm making this contribution on behalf of @mightylibrarian about episode 1. Please direct your questions to @mightylibrarian. Thanks!

I think using the same term "mark" is best for lines 56 to 59, easier to compare and allows instruction to ask for other terms using terms: word, comb, and respect.

	- the regular expression `mark` will match not only `mark` but also find `marking`, `market`, `unremarkable`, and so on.
	- the regular expression `\bmark` will match `mark`, `marking`, and `marketable`, but not 'remark' or 'demark'.
	- the regular expression `mark\b` will match `mark` and `remark` but not `market`.
	- the regular expression `\bmark\b` will match `mark` but not `marking' or `unremarkable`.

**Comment by sharilaster** [comment]
It looks like this is duplicated in #189 so I'll close this version. Thank you @fmichonneau!
