### ISSUE TITLE
Scheduling early transition to Workbench

### ISSUE THREAD

**Issue by tobyhodges** [LibraryCarpentry/lc-data-intro#203]
Short version: **are you are willing to volunteer your lesson for early transition to The Carpentries Workbench 
infrastructure?**

---

Longer version below:

As I hope you are already aware, @zkamvar and the rest of the Curriculum Team are preparing to roll out the new lesson infrastructure, [The Carpentries Workbench](https://carpentries.github.io/workbench/), across all of The Carpentries official lessons in early May 2023. This means that all Data Carpentry, Library Carpentry, and Software Carpentry lesson repositories will be modified to adopt the new infrastructure at the end of this month.

As you might imagine, coordinating a rollout like this involves a large amount of time and effort, and one thing that will really help us to keep to the schedule and avoid disruption for the community is to be able to **prepare some lessons for 
transition before the 1st May deadline**.

With this in mind, **I invite you to volunteer to schedule an early transition for theis lesson repository.** If you expect to have time to adopt the Workbench version of the lesson repository in the next couple of weeks, please reply to let me know. As lesson Maintainers, these are the things you will need to be prepared to do for the transition:
1. **Be prepared to quickly merge pull requests from Zhian**. These pull requests will help update the lesson and aid the transition process.
2. **Close any outstanding pull requests.** Your repository currently has very few or zero open PRs, but we cannot rule out the possibility that someone will open more in the time between now and when the transition takes place. [Open PRs will be invalidated when the transition takes place](https://carpentries.github.io/sandpaper-docs/pull-request.html#transition-from-carpentriesstyles).
3. **Preview the lesson (in the https://github.com/fishtree-attempt organisation) when it is available**. Zhian will open an issue in your repository, tagging you when the preview is available. You should reply on that issue if you notice any problems with the Workbench version of the lesson site and repository in the preview.
4. Just before the transition happens, the repository will be temporarily set as read-only and an issue will be opened (see an example from the Maintainer Onboarding curriculum: https://github.com/carpentries/maintainer-onboarding/issues/69) 
5. After the transition, **delete and recreate any forks and local clones** you have of the repository and then **confirm that you have done so** (you will be given specific instructions in an issue).

If you are willing and able to help us ensure a smooth rollout of the Workbench, please reply to let me know that you are happy to volunteer your lesson for early transition. If there is a specific date you would like the transition to take place (or that we should avoid), please also mention that.

**Comment by sharilaster** [comment]
Hi @tobyhodges, thanks for reaching out! 

As you can see we've got two open PRs. The old one is really an issue, not a PR. I opened an issue and mentioned it, but if I close the PR without completing the work for the issue, will the PR still show up for the issue?

The other one is a formatting PR. I think someone will need to check and see if the formatting request is compliant with the styling or not. I am not quite sure how to do this myself, and not sure if there's anyone on the maintainer team who can check on this? We do need to at least respond to this person before closing out the PR.

Once these two PRs are resolved, we can set up a time for the transition -- it won't be a problem to quickly merge PRs associated with the transition and check to see everything looks ok.

**Comment by sharilaster** [comment]
Thank you, I appreciate the assist on the formatting PR! 

For #184, the original contributor suggested some language changes but left an example blank. We've had discussion about the example in the associated issue, but that's still open. And meanwhile, another contributor proposed changes to the language from the first contributor, but did not add a PR. Do you have any advice on how to resolve this? I'm afraid I am not familiar with how to directly changing PRs.

**Comment by zkamvar** [comment]
Hello,

This help document shows how you can suggest a change on the pull request (steps 4 and 5):

https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/commenting-on-a-pull-request

Note that you can click on a line number and drag it down to make changes to the original.

After you suggest the changes, you can immediately commit them as shown here: https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/incorporating-feedback-in-your-pull-request#applying-suggested-changes

You can also merge the pull request and then immediately make another pull request to update the text with the language you want.

**Comment by zkamvar** [comment]
I am planning to transition this lesson on 03 May, but we can delay if needed.

**Comment by sharilaster** [comment]
That was exactly what I needed!!! Thank you @zkamvar. Confirming yes, 03 May will work for the lesson transition.

**Comment by sharilaster** [comment]
Thank you for your efforts to make this transition go smoothly for us!!
