### ISSUE TITLE
Broken link to domain name list

### ISSUE THREAD

**Issue by aforestsomewhere** [LibraryCarpentry/lc-data-intro#219]
### What is the problem?

In [2. Matching & Extracting Strings > Exercise finding email addresses using regex101.com > Finish the Expression](https://librarycarpentry.org/lc-data-intro/instructor/02-match-extract-strings.html#exercise-finding-email-addresses-using-regex101.com), there is a broken link labelled "here" to common domain names directing to https://stats.research.icann.org/dns/tld_report/

Possible alternatives: 
https://data.iana.org/TLD/tlds-alpha-by-domain.txt 
https://publicsuffix.org/list/public_suffix_list.dat

Happy to submit a PR if it helps!

### Location of problem (optional)

https://librarycarpentry.org/lc-data-intro/instructor/02-match-extract-strings.html#exercise-finding-email-addresses-using-regex101.com

**Comment by kevintfrench** [comment]
Thank you for noticing this @aforestsomewhere .  Yes, I'd like to take you up on your offer to create a PR.  Thank you!

**Comment by aforestsomewhere** [comment]
Submitted a PR there!
