### ISSUE TITLE
Summary/setup refers to a (maybe?) deprecated lesson

### ISSUE THREAD

**Issue by maneesha** [LibraryCarpentry/lc-data-intro#227]
### What is the problem?

In the [summary/setup section](https://librarycarpentry.org/lc-data-intro/index.html), the [first callout]( https://librarycarpentry.org/lc-data-intro/index.html#teaching-this-lesson) says this can be taught alongside  [Jargon Busting](https://librarycarpentry.org/lc-overview/03-jargon-busting) and [A Computational Approach](https://librarycarpentry.org/lc-overview/04-computational-approach) in [Workshop Overview](https://librarycarpentry.org/lc-overview/).

There seem to be plans to deprecate the LC overview lessons.  See [current page](https://librarycarpentry.org/lc-overview/) which says it will be retired on 2024-03-29 and a [bunch of issues in that repo](https://github.com/LibraryCarpentry/lc-overview/issues) referencing decomissioning this lesson.

### Location of problem (optional)

https://librarycarpentry.org/lc-data-intro/index.html#teaching-this-lesson

**Comment by kevintfrench** [comment]
Thank you @maneesha I've removed the links and references to the deprecated LC Overview lesson.
