### ISSUE TITLE
We are no longer using Twitter 

### ISSUE THREAD

**Issue by maneesha** [LibraryCarpentry/lc-data-intro#228]
### What is the problem?

The [regex discussion section](https://librarycarpentry.org/lc-data-intro/discuss.html) suggests following LC on Twitter.  Recommend removing this and offering other forms of engagement.

### Location of problem (optional)

https://librarycarpentry.org/lc-data-intro/discuss.html

**Comment by kevintfrench** [comment]
Thank you @maneeesha I've removed the line regarding Twitter.  I'm not aware of other areas to engage but will add them if/when I come across them.

**Comment by maneesha** [comment]
Thanks.  Tagging @OscarSiba for recommendations on what we should include instead.

**Comment by OscarSiba** [comment]
I also recommend we add our Mastodon account (https://hachyderm.io/@thecarpentries) and LinkedIn account (https://www.linkedin.com/company/the-carpentries/) @maneesha @kevintfrench. Thank you.

**Comment by kevintfrench** [comment]
Hi, 
Sorry for the delay, I've been dealing with a crises.  I've added Mastodon and LinkedIn.  I appreciate all the help @maneesha and @OscarSiba (especially going the extra mile to get the links!)
