### ISSUE TITLE
Curriculum request: Update estimated lesson length

### ISSUE THREAD

**Issue by chennesy** [LibraryCarpentry/lc-data-intro#236]
### How could the content be improved?

The @LibraryCarpentry/curriculum-advisors  recently updated the [LC lessons page](https://librarycarpentry.org/lessons/) to add a column with an estimated length for each lesson that workshop organizers can use to help them plan workshops. We used estimated times from the [YAML `teaching` and `exercises` metadata fields ](https://carpentries.github.io/sandpaper-docs/episodes.html#yaml-metadata)from your lesson to come up with the initial estimated length. Two requests:

1. Please reply here if you want to suggest a different estimated length for the lessons page and I will update it there.
2. If our estimate was incorrect, it would be great if you can update the episode YAML metadata to reflect more accurate times.

If the estimated time looks good to you, feel free to close this issue.

**Comment by kevintfrench** [comment]
Thank you, @chennesy that looks like a good estimate to me.
