### ISSUE TITLE
Rename "Data Intro for Librarians" to "for Libraries"?

### ISSUE THREAD

**Issue by kristindawn** [LibraryCarpentry/lc-data-intro#39]
The title "Data Intro for Librarians" leaves out a significant group of people who work in libraries but who aren't librarians. This can be a point of contention at some libraries and can leave people feeling unwelcome. I don't know if "For Libraries" is the best wording, but for Librarians could be alienating for library staff and other specialists without ML(I)Ss.

**Comment by weaverbel** [comment]
We could just call it Data Intro.

**Comment by libcce** [comment]
I completely agree @kristindawn! We can try "Library Carpentry: Intro to Data" or "Intro to Data for Libraries"? We will have to make this change globally to other lessons as well... if others agree?

**Comment by ccronje** [comment]
It's a good point @kristindawn, and would be good to address across lessons. My vote is "Library Carpentry: Introduction to Data".

**Comment by weaverbel** [comment]
Title changed to Library Carpentry: Introduction to Data
