### ISSUE TITLE
Incorporate parts of tidy spreadsheets into data-intro

### ISSUE THREAD

**Issue by jt14den** [LibraryCarpentry/lc-data-intro#41]
Chatted with @jezcope a bit at carpentrycon and we thought parts of [lc-spreadsheets]( https://librarycarpentry.github.io/lc-spreadsheets/) can be utilized in data-intro. For example, [Episode 1](https://librarycarpentry.github.io/lc-spreadsheets/01-format-data/) can be a stand-alone module and used in data-intro.

**Comment by ccronje** [comment]
@jt14den @jezcope I really like lc-spreadsheets as a standalone lesson but this could be a good approach as well. Do you see episode 1 of lc-spreadsheets replacing some data-intro content or weaving it into a particular episode, or creating a new episode? Maybe it would be good to map out which parts you want to use and where they could fit in.

**Comment by jt14den** [comment]
@ccronje @jezcope as part of teaching at USC next month, I'm going to experiment with this. The hosts didn't want our regex episode in intro-data, so we'll try to add tidy data at that point. I'll make a fork and share what we come up with.

**Comment by ccronje** [comment]
Hi @jt14den @jezcope? How did this go? Do you still think we should do this? What do others think?

**Comment by jezcope** [comment]
@jt14den Ooh, yes, I'd be interested to find out how this went.

**Comment by drjwbaker** [comment]
Bumping. Any maintainer want to take this?

**Comment by ccronje** [comment]
@drjwbaker @sharilaster @ppival @antonangelo - since there is a separate Tidy Data LC lesson https://librarycarpentry.org/lc-spreadsheets/, perhaps the next action here is to identify which section(s) in Tidy Data you think would be helpful to link to.

**Comment by libcce** [comment]
The Workshop Overview lesson should address some/all of these points: https://librarycarpentry.org/lc-overview/ If nobody responds, we can close this issue. Thanks everyone for your feedback!
