### ISSUE TITLE
Move References

### ISSUE THREAD

**Issue by ccronje** [LibraryCarpentry/lc-data-intro#46]
@jt14den suggested we move the References listed at the bottom of https://librarycarpentry.github.io/lc-data-intro/04-regular-expressions/

Where should we move them to?
1. A separate episode at the end of lesson?
2. Under Extras > Reference? https://librarycarpentry.github.io/lc-data-intro/reference/

**Comment by jt14den** [comment]
Looking at the lesson example documentation: https://swcarpentry.github.io/lesson-example/03-organization/index.html

I think `reference.md` the best place for references. I started to look for similar things in some of the SWC lessons, but gave up.

**Comment by ccronje** [comment]
Thanks @jt14den, I moved the Refs to `reference.md`
