### ISSUE TITLE
Setup page style and navigation header don't match other lesson pages

### ISSUE THREAD

**Issue by jbkieffer** [LibraryCarpentry/lc-data-intro#49]
The setup page for this lesson (and, actually, all the lessons I've looked at) is using the default browser style instead of the Carpentries style. See https://librarycarpentry.github.io/lc-data-intro/setup/ 

Also, the top navigation bar is pointing to directories that don't exist - it looks as if a subdirectory "setup" has been hard coded into the page:
https://github.com/LibraryCarpentry/lc-data-intro/blob/gh-pages/setup.md

**Comment by jbkieffer** [comment]
FYI, this also seems to be an identical issue for the Reference page: 
https://librarycarpentry.github.io/lc-data-intro/reference/

**Comment by weaverbel** [comment]
Is this a styles issue @rgaiacs ?I am not sure how to fix it.

**Comment by weaverbel** [comment]
I think I have fixed this @rgaiacs @jbkieffer

**Comment by rgaiacs** [comment]
> Is this a styles issue

You should not have `permlink` in the YAML header.

**Comment by weaverbel** [comment]
Agree. Removed them.
