### ISSUE TITLE
 Checkout contribution for instructor training - Peter Rolla

### ISSUE THREAD

**Issue by sheraaron** [LibraryCarpentry/lc-data-intro#57]
I have discovered a typo that is creating a broken link on a Library Carpentry lesson page and I would like to submit it as my check-out contribution (I was in the Calgary instructor training on August 30-31, 2018).

The typo in question is on the page Library Carpentry: Introduction to Data: Instructor Notes, at https://librarycarpentry.github.io/lc-data-intro/guide/. The first heading "Making a handout" has the text:

Librarians like handouts. To make a handout for this lesson, adapt/print from https://librarycarpentry.github.io/lc-data-intro/reference/.

That link doesn't work and leads to an error page. The problem seems to be the slash mark at the end of the URL. If corrected to https://librarycarpentry.github.io/lc-data-intro/reference then the link works fine.

**Comment by libcce** [comment]
Fixed with https://github.com/LibraryCarpentry/lc-data-intro/commit/efc8eb2c649839bf16681ccc314b532e7dc7d286 Thanks!
