### ISSUE TITLE
Recommend Atom as editor

### ISSUE THREAD

**Issue by katrinleinweber** [LibraryCarpentry/lc-data-intro#67]
[We currently recommend Notepad++](https://github.com/LibraryCarpentry/lc-data-intro/blob/f583d403dc97200fb908f150b44d8468274d99b4/_episodes/03-foundations.md#applications-for-writing-reading-and-outputting-plain-text-files) to Windows users and mention Atom only briefly. Because of its [Teletype](https://github.com/blog/2468-introducing-teletype-for-atom-code-collaboratively-in-real-time) capability and [integration with GitHub Desktop](https://help.github.com/desktop/guides/getting-started-with-github-desktop/configuring-a-default-editor/), how about we recommend it specifically?

PS: GitHub Desktop could also be somewhat central goal for Library Carpentry to move towards, because it brings the Git Bash with it as well, and there is a [derivative lesson](https://github.com/caltechlibrary/git-desktop).

**Comment by drjwbaker** [comment]
Just flagging that we've had an argument in the past about Atom https://github.com/LibraryCarpentry/librarycarpentry.github.io/issues/24 tl;dr: instructors have reported the download overhead and cognitive overload of atom to be a problem.

**Comment by libcce** [comment]
Thanks @drjwbaker! This is probably something for the new Maintainers to revisit and possibly discuss. Which reminds me, I really need to prompt the groups to meet!

**Comment by drjwbaker** [comment]
Good idea. For what it is worth, I think this should be more about getting across *why* use a text editor than *which* text editor to use.

**Comment by ccronje** [comment]
@libcce recommends closing this issue and creating a new issue as per @drjwbaker's comment 'add section on why use a text editor'. Would you like to do that @sharilaster @ppival @antonangelo ? It would be a good one to label mozsprint too.

As well as the tools listed here, @libcce recommends noting https://regexr.com/, brackets.io, Atom.

**Comment by libcce** [comment]
Thanks @ccronje! I've created https://github.com/LibraryCarpentry/lc-data-intro/issues/98.
