### ISSUE TITLE
No mention of the many regular expression engines in use nor the engine used in the lesson's examples

### ISSUE THREAD

**Issue by andrewrs** [LibraryCarpentry/lc-data-intro#71]
I'd recommend mentioning, at least in passing, that there are many different regular expression engines in common use and that each engine has features and syntax that, while often quite similar, do differ from each other in meaningful ways.   

Additionally, there is no mention of the specific engine used for the lesson's examples. Granted, the basic  examples used in the lesson will work with any Perl-like engine (with the lesson's suggested online tools employing PCRE and Javascript for the most part), it would be a good thing to plant the idea in the head of students that they might need to learn a particular tool or language's regular expression implementation before using more advanced regex features. 

A couple links that describe the varying features of some of the many regular expression engines in use:
https://en.wikipedia.org/wiki/Comparison_of_regular_expression_engines (basic overview as one would expect on wikipedia)
https://www.regular-expressions.info/refflavors.html (nice, detailed reference)

**Comment by libcce** [comment]
+1 I often note this in my workshops but it would be great to reference one or two the links that you point to for more information. Can you see a point in the lesson where we can add this?

**Comment by andrewrs** [comment]
I think adding 2-3 sentences in the lesson's opening paragraph would be sufficient and then maybe adding the links to the Key Points section.

**Comment by drjwbaker** [comment]
@andrewrs Would you be willing and able to recommend some text? I'm aware that there are different flavours of regex, but you seem to no more about the details than I do.

**Comment by andrewrs** [comment]
Here's my first crack at some text:

> Most regular expression implementations employ comparable syntaxes (generally influenced by the Perl programming language's regex syntax) that behave similarly for simple pattern-matching operations. But there are differences, often subtle, in each, so it's always a good practice to read application or language's documentation whenever available, especially if you want to start using more advanced regex features.  Some programs, notably many UNIX command line programs, use an older regex standard (POSIX regular expressions) which is less feature-rich and employs different metacharacters than Perl-influenced implementations .  

I'll see if I can write something a little more tight over the next couple days when I'm not suffering from Friday afternoon brain fade.

I also came across another nice reference at: https://gist.github.com/CMCDragonkai/6c933f4a7d713ef712145c5eb94a1816

**Comment by drjwbaker** [comment]
Many thanks. I like it. Shall we go with:

> Most regular expression implementations employ comparable syntaxes (generally influenced by the regex syntax of a programming language called Perl) that behave similarly for most pattern-matching operations. But there are differences, often subtle, in each, so it's always a good practice to read application or language's documentation whenever available, especially if you want to start using more advanced regex features. Some programs, notably many UNIX command line programs (for more on UNIX see our '[Shell Lesson](https://librarycarpentry.org/lc-shell/)'), use an older regex standard (called 'POSIX regular expressions') which is less feature-rich and employs different metacharacters than Perl-influenced implementations. For the purposes of our lesson, you don't need to worry too much about all this, but if you want to follow up on this see [this detailed engine comparison](https://gist.github.com/CMCDragonkai/6c933f4a7d713ef712145c5eb94a1816).

I suggest we add it between '..including markdown and HTML.' and 'A very simple use of a regular expression..' at https://librarycarpentry.org/lc-data-intro/04-regular-expressions/index.html as a pinned callout (like 'Tab for Auto-complete' at https://librarycarpentry.org/lc-shell/03-working-with-files-and-folders/index.html).

PR here https://github.com/LibraryCarpentry/lc-data-intro/pull/73

**Comment by andrewrs** [comment]
Yeah, I was thinking that placing the new text between '..including markdown and HTML.' and 'A very simple use of a regular expression..' too.   

I forked and the previously referenced regex feature comparison and separated the feature categories  into their own tables to allow for easier scrolling:
https://gist.github.com/andrewrs/74ece75269f56d074408df216b3d9e77

I like your edits and additions and I think version you posted is good to go.  Yesterday, I revised my initial draft to come up with:

> Most regular expression implementations employ comparable syntaxes and metacharacters (generally influenced by the Perl programming language's regex syntax), and they behave similarly for the simple pattern-matching exercises in this lesson. But there are differences, often subtle, in each, so it's always a good practice to read application or language's documentation whenever available, especially when you start using more advanced regex features. Some programs, notably many UNIX command line programs, use an older regex standard (POSIX regular expressions) which is less feature-rich and uses different metacharacters than Perl-influenced implementations. Reference the links at the end of this lesson for greater detail. 

Sorry for the delay in posting the revision.  Github apparently determined that my final edits to the regex table mentioned above weren't adequately human-like and locked my account for a day until I could customer service to unlock it.

Feel free to pick and choose from either version.  Again, I think the  version you posted is perfectly sufficient.

**Comment by drjwbaker** [comment]
@andrewrs Woah, weird bot drama! I've incorporated your revised text into the PR. Ta!

**Comment by drjwbaker** [comment]
Resolved by https://github.com/LibraryCarpentry/lc-data-intro/pull/73
