### ISSUE TITLE
Give this lesson a clear purpose

### ISSUE THREAD

**Issue by drjwbaker** [LibraryCarpentry/lc-data-intro#80]
As we've removed the 'history' stuff from this lesson and as we know that many people teach this a different way, this year is a good time to think about what we really want to achieve with this lesson. For me the keys are:

- an ice breaker that helps attendees feel comfortable about what they do/don't know.
- a simple intro to 'programming', programmatic thinking, and how an LC workshop works ('regex' works well)
- an opportunity to think about the connection between library work and programmatic tasks.

**Comment by drjwbaker** [comment]
Building on https://github.com/LibraryCarpentry/lc-data-intro/issues/51#issuecomment-454019967

**Comment by jt14den** [comment]
I  see two purposes: an intro to programming and an intro to concepts for working with untidy data. The intro to data (tidy data) is continued thru OpenRefine whereas bash introduces core programming concepts. I personally think we should incorporate concepts in 'tidy data in a spreadsheet' as part of this lesson and make sure we build upon those concepts in OR.

**Comment by drjwbaker** [comment]
Thanks @jt14den. Parts of https://librarycarpentry.org/lc-data-intro/03-foundations/index.html do that already, albeit not very well. Feels like we could reorganise this into three parts:

1) jargon busting (icebreaker)
2) from untidy to tidy data (principles)
3) regex (first intro to programming)

1 and 3 are there. So this would just require some proper thinking about 2.

**Comment by ccronje** [comment]
Maintainers @sharilaster @antonangelo @ppival have sought feedback from instructors of this lesson. This will clarify the purpose of this lesson (what has worked well, what could be improved etc). We hope to discuss this in May before the Mozilla Sprint.

**Comment by drjwbaker** [comment]
fyi I'll struggle to make the sprint, but if you need my input to copy edit the revised lesson, happy to.

**Comment by ccronje** [comment]
Closing this issue. Will open a new issue once feedback from trainers collected (see https://github.com/LibraryCarpentry/lc-data-intro/issues/80#issuecomment-489387974)
