### ISSUE TITLE
Rework first lesson 01-introduction.md - move info about library carpentry to website or workshop template

### ISSUE THREAD

**Issue by jt14den** [LibraryCarpentry/lc-data-intro#9]
As we develop library carpentry into a lesson organization, we should move information about the program out of the intro lesson an into the website or workshop template. This first episode should be re-written to include an intro do the first lesson "data intro". One suggestion will be supply an intro to what will be covered in the lesson: 

* breaking down jargon tech terms that confuse
* why we'd want to automate things thru computation
* how using flat files and naming conventions enables automation
* why pattern matching is powerful

**Comment by yvonnemery** [comment]
We tried rewriting some of the introduction. Information about the history of the program should be deleted from here and placed in the About page.

**Comment by drjwbaker** [comment]
I think this can be closed now. Do reopen if I'm wrong! (cc @ccronje)
