### ISSUE TITLE
Review guide.md against Carpentries style guide

### ISSUE THREAD

**Issue by libcce** [LibraryCarpentry/lc-data-intro#94]
Carpentries now has a style guide
https://docs.carpentries.org/topic_folders/communications/style-guide.html

Review guide.md (https://github.com/LibraryCarpentry/lc-data-intro/blob/gh-pages/_extras/guide.md) to ensure it follows the style guide

**Comment by remerjohnson** [comment]
I put in a PR for this. Was mostly just cleaning up bullets and minor spelling/grammar fixes.

**Comment by libcce** [comment]
Thanks @remerjohnson 😄
