### ISSUE TITLE
Add section on why use a text editor

### ISSUE THREAD

**Issue by libcce** [LibraryCarpentry/lc-data-intro#98]
Instead of recommending specific text editors in [Applications for writing, reading and outputting plain text files](https://github.com/LibraryCarpentry/lc-data-intro/blob/gh-pages/_episodes/03-foundations.md) address why a text editor is helpful. List additional tools that might be missing. 

For further background, see https://github.com/LibraryCarpentry/lc-data-intro/issues/67.

**Comment by michaelhagedon** [comment]
I tried to keep this new content from duplicating what's already discussed earlier in the lesson about plain text formats. Others can decide how successful that was. :-)

**Comment by libcce** [comment]
@michaelhagedon I think we made the change you suggested? This might be a duplication? Please let us know?
